
name: Publish Python Package

on:
  workflow_run:
    workflows: ["Build Python Package"]
    types:
      - completed
    branches:
      - main

env:
  CLOUDSMITH_NAMESPACE: ${{ secrets.CLOUDSMITH_NAMESPACE }}
  CLOUDSMITH_REPOSITORY: "staging"
  CLOUDSMITH_SERVICE_SLUG: ${{ secrets.CLOUDSMITH_SERVICE_SLUG }}

permissions:
  contents: read
  actions: read
  id-token: write
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Download artifact
        uses: actions/github-script@v7
        with:
          script: |
            const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.payload.workflow_run.id,
            });
            const matchArtifact = artifacts.data.artifacts.find((artifact) => {
              return artifact.name === 'python-package'
            });
            if (!matchArtifact) {
              throw new Error('No artifact found');
            }
            const download = await github.rest.actions.downloadArtifact({
              owner: context.repo.owner,
              repo: context.repo.repo,
              artifact_id: matchArtifact.id,
              archive_format: 'zip'
            });
            const fs = require('fs');
            fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/artifact.zip`, Buffer.from(download.data));
      - name: Unzip artifact
        run: |
          mkdir -p dist
          unzip artifact.zip -d dist
      - name: List directory contents
        run: ls -la dist/
        shell: bash
      - name: Install Cloudsmith CLI
        run: |
          pip install --upgrade cloudsmith-cli
      - name: Authenticate with Cloudsmith (OIDC)
        id: auth
        run: |
          # Request the GitHub OIDC token
          oidc_token=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=api://AzureADTokenExchange" | jq -r '.value')
          # Exchange the OIDC token for a Cloudsmith token
          cloudsmith_token=$(curl -X POST -H "Content-Type: application/json" \
            -d "{\"oidc_token\":\"$oidc_token\", \"service_slug\":\"${{ env.CLOUDSMITH_SERVICE_SLUG }}\"}" \
            https://api.cloudsmith.io/openid/${{ env.CLOUDSMITH_NAMESPACE }}/ | jq -r '.token')
          # Store the Cloudsmith token as an environment variable
          echo "CLOUDSMITH_API_KEY=$cloudsmith_token" >> $GITHUB_ENV
      - name: Find the Built Package
        id: find_package
        run: |
          PACKAGE_FILE=$(ls dist/*.tar.gz dist/*.whl 2>/dev/null | head -n 1)
          if [ -z "$PACKAGE_FILE" ]; then
            echo "No file found in dist/"
            exit 1
          fi
          echo "Found package: $PACKAGE_FILE"
          echo "PACKAGE_PATH=$PACKAGE_FILE" >> $GITHUB_ENV
      - name: Push package to Cloudsmith
        env:
            CLOUDSMITH_API_KEY: ${{ env.CLOUDSMITH_API_KEY }}
        run: |
            if ! ls dist/*.tar.gz 1> /dev/null 2>&1; then
              echo "No package found to upload"
              exit 1
            fi
            cloudsmith push python ${{ env.CLOUDSMITH_NAMESPACE }}/${{ env.CLOUDSMITH_REPOSITORY }} dist/*.tar.gz "${{ env.PACKAGE_PATH }}" --republish --api-key $CLOUDSMITH_API_KEY